"""Add check_at col to Puzzle

Revision ID: 80e098498bea
Revises: 949576c81223
Create Date: 2026-02-02 21:31:04.962016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80e098498bea'
down_revision: Union[str, Sequence[str], None] = '949576c81223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'checked_at')
    # ### end Alembic commands ###
