"""move delete lichess to puzzle col

Revision ID: 202e1175c2fb
Revises: 80e098498bea
Create Date: 2026-02-02 22:18:24.901920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "202e1175c2fb"
down_revision: Union[str, Sequence[str], None] = "80e098498bea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE puzzle
        SET deleted_at = pr.is_deleted_from_lichess
        FROM puzzlereport AS pr
        WHERE
            puzzle.lichess_id = pr.puzzle_id
            AND pr.is_deleted_from_lichess IS NOT NULL
            AND puzzle.deleted_at IS NULL;
        """)
    op.drop_column("puzzlereport", "is_deleted_from_lichess")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "puzzlereport",
        sa.Column("is_deleted_from_lichess", sa.DATETIME(), nullable=True),
    )
    op.execute("""
        UPDATE puzzlereport
        SET is_deleted_from_lichess = p.deleted_at
        FROM puzzle AS p
        WHERE puzzlereport.puzzle_id = p.lichess_id;
        """)
    # ### end Alembic commands ###
