# b"{'board': Board('Q6Q/8/8/2p3k1/5pq1/1P4pK/5P2/8 w - - 1 57'), 'limit': Limit(depth=50, nodes=25000000), 'multipv': 5}"
[
    {
        "currmove": Move.from_uci("h3g2"),
        "currmovenumber": 1,
        "depth": 50,
        "hashfull": 979,
        "lowerbound": True,
        "multipv": 1,
        "nodes": 23949347,
        "nps": 1639804,
        "pv": [
            Move.from_uci("h3g2"),
            Move.from_uci("g3f2"),
            Move.from_uci("g2f2"),
            Move.from_uci("g4g3"),
            Move.from_uci("f2e2"),
            Move.from_uci("g3e3"),
            Move.from_uci("e2d1"),
            Move.from_uci("e3b3"),
            Move.from_uci("d1d2"),
            Move.from_uci("b3e3"),
            Move.from_uci("d2c2"),
            Move.from_uci("e3e2"),
            Move.from_uci("c2c3"),
            Move.from_uci("e2e1"),
            Move.from_uci("c3c4"),
            Move.from_uci("e1f1"),
            Move.from_uci("c4d5"),
            Move.from_uci("f1d1"),
            Move.from_uci("d5e6"),
            Move.from_uci("d1g4"),
            Move.from_uci("e6d6"),
            Move.from_uci("g4d1"),
            Move.from_uci("a8d5"),
            Move.from_uci("d1d5"),
            Move.from_uci("d6d5"),
            Move.from_uci("c5c4"),
            Move.from_uci("h8g7"),
            Move.from_uci("g5f5"),
            Move.from_uci("g7f7"),
            Move.from_uci("f5g4"),
            Move.from_uci("d5e4"),
            Move.from_uci("g4g3"),
            Move.from_uci("f7f4"),
            Move.from_uci("g3g2"),
            Move.from_uci("e4e3"),
            Move.from_uci("g2g1"),
            Move.from_uci("f4f2"),
            Move.from_uci("g1h1"),
            Move.from_uci("e3f3"),
            Move.from_uci("c4c3"),
            Move.from_uci("f2g2"),
        ],
        "score": PovScore(Mate(+21), WHITE),
        "seldepth": 42,
        "string": "Network replica 1: Local memory. Shared memory not supported by "
        "the OS. Local allocation fallback.",
        "tbhits": 0,
        "time": 14.605,
    }
]
