# b"{'board': Board('8/5k2/8/1PpP4/K4p2/5P2/2r3p1/4R3 b - - 1 50'), 'limit': Limit(depth=50, nodes=25000000), 'multipv': 5}"
[
    {
        "string": "NNUE evaluation using nn-37f18f62d772.nnue (6MiB, (22528, 128, 15, 32, 1))",
        "depth": 29,
        "seldepth": 63,
        "multipv": 1,
        "score": PovScore(Cp(+523), BLACK),
        "nodes": 25000591,
        "nps": 972142,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 25.717,
        "pv": [
            Move.from_uci("c2a2"),
            Move.from_uci("a4b3"),
            Move.from_uci("a2f2"),
            Move.from_uci("e1g1"),
            Move.from_uci("f2f3"),
            Move.from_uci("b3c2"),
            Move.from_uci("f3f2"),
            Move.from_uci("c2d3"),
            Move.from_uci("f4f3"),
            Move.from_uci("b5b6"),
            Move.from_uci("f2b2"),
            Move.from_uci("d3e3"),
            Move.from_uci("b2b3"),
            Move.from_uci("e3f2"),
            Move.from_uci("f7e7"),
            Move.from_uci("b6b7"),
            Move.from_uci("e7d6"),
            Move.from_uci("b7b8r"),
            Move.from_uci("b3b8"),
            Move.from_uci("f2f3"),
            Move.from_uci("b8f8"),
            Move.from_uci("f3g2"),
            Move.from_uci("f8g8"),
            Move.from_uci("g2f2"),
            Move.from_uci("g8g1"),
            Move.from_uci("f2g1"),
            Move.from_uci("d6d5"),
            Move.from_uci("g1f2"),
            Move.from_uci("d5c4"),
        ],
        "currmove": Move.from_uci("c2a2"),
        "currmovenumber": 1,
    },
    {
        "depth": 29,
        "seldepth": 72,
        "multipv": 2,
        "score": PovScore(Cp(+490), BLACK),
        "nodes": 25000591,
        "nps": 972142,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 25.717,
        "pv": [
            Move.from_uci("c2f2"),
            Move.from_uci("e1g1"),
            Move.from_uci("f7f6"),
            Move.from_uci("d5d6"),
            Move.from_uci("f6e6"),
            Move.from_uci("b5b6"),
            Move.from_uci("f2b2"),
            Move.from_uci("a4a3"),
            Move.from_uci("b2b6"),
            Move.from_uci("g1g2"),
            Move.from_uci("b6d6"),
            Move.from_uci("a3b2"),
            Move.from_uci("d6d3"),
            Move.from_uci("g2g5"),
            Move.from_uci("c5c4"),
            Move.from_uci("g5c5"),
            Move.from_uci("d3f3"),
            Move.from_uci("b2c2"),
            Move.from_uci("f3e3"),
            Move.from_uci("c5c4"),
            Move.from_uci("e6f5"),
            Move.from_uci("c2d2"),
            Move.from_uci("f5g4"),
            Move.from_uci("c4c8"),
            Move.from_uci("e3e5"),
            Move.from_uci("d2d3"),
            Move.from_uci("f4f3"),
            Move.from_uci("c8f8"),
            Move.from_uci("g4g3"),
            Move.from_uci("f8f6"),
            Move.from_uci("f3f2"),
            Move.from_uci("f6g6"),
            Move.from_uci("g3h2"),
            Move.from_uci("g6f6"),
            Move.from_uci("h2g1"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 57,
        "multipv": 3,
        "score": PovScore(Cp(+42), BLACK),
        "nodes": 25000591,
        "nps": 972142,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 25.717,
        "pv": [
            Move.from_uci("c2b2"),
            Move.from_uci("d5d6"),
            Move.from_uci("b2e2"),
            Move.from_uci("e1g1"),
            Move.from_uci("f7e6"),
            Move.from_uci("a4b3"),
            Move.from_uci("e6d6"),
            Move.from_uci("b3c4"),
            Move.from_uci("e2d2"),
            Move.from_uci("c4c3"),
            Move.from_uci("d2f2"),
            Move.from_uci("c3c4"),
            Move.from_uci("f2f3"),
            Move.from_uci("g1g2"),
            Move.from_uci("f3f1"),
            Move.from_uci("c4d3"),
            Move.from_uci("f4f3"),
            Move.from_uci("g2b2"),
            Move.from_uci("c5c4"),
            Move.from_uci("d3e3"),
            Move.from_uci("c4c3"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 40,
        "multipv": 4,
        "score": PovScore(Cp(+22), BLACK),
        "nodes": 25000591,
        "nps": 972142,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 25.717,
        "pv": [
            Move.from_uci("c2e2"),
            Move.from_uci("e1g1"),
            Move.from_uci("e2b2"),
            Move.from_uci("a4a3"),
            Move.from_uci("b2b5"),
            Move.from_uci("g1g2"),
            Move.from_uci("f7f6"),
            Move.from_uci("g2e2"),
            Move.from_uci("b5b6"),
            Move.from_uci("e2e8"),
            Move.from_uci("f6f5"),
            Move.from_uci("a3a4"),
            Move.from_uci("b6d6"),
            Move.from_uci("a4b3"),
            Move.from_uci("d6d5"),
            Move.from_uci("e8f8"),
            Move.from_uci("f5g5"),
            Move.from_uci("b3c4"),
            Move.from_uci("d5d1"),
            Move.from_uci("f8g8"),
            Move.from_uci("g5f5"),
            Move.from_uci("c4c5"),
            Move.from_uci("d1d3"),
            Move.from_uci("g8f8"),
            Move.from_uci("f5g5"),
            Move.from_uci("f8g8"),
            Move.from_uci("g5h4"),
            Move.from_uci("g8g4"),
            Move.from_uci("h4h3"),
            Move.from_uci("g4f4"),
            Move.from_uci("h3g3"),
            Move.from_uci("f4f6"),
            Move.from_uci("g3f2"),
            Move.from_uci("f3f4"),
            Move.from_uci("f2e3"),
            Move.from_uci("f4f5"),
            Move.from_uci("d3d7"),
            Move.from_uci("f6e6"),
            Move.from_uci("e3f3"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 52,
        "multipv": 5,
        "score": PovScore(Cp(+21), BLACK),
        "nodes": 25000591,
        "nps": 972142,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 25.717,
        "pv": [
            Move.from_uci("c2d2"),
            Move.from_uci("b5b6"),
            Move.from_uci("d2f2"),
            Move.from_uci("e1g1"),
            Move.from_uci("f2b2"),
            Move.from_uci("b6b7"),
            Move.from_uci("b2b4"),
            Move.from_uci("a4a5"),
            Move.from_uci("b4b7"),
            Move.from_uci("g1g2"),
            Move.from_uci("f7f6"),
            Move.from_uci("g2e2"),
            Move.from_uci("b7d7"),
            Move.from_uci("a5b5"),
            Move.from_uci("d7d5"),
            Move.from_uci("b5c4"),
            Move.from_uci("d5g5"),
            Move.from_uci("e2e4"),
            Move.from_uci("f6f5"),
            Move.from_uci("c4d5"),
            Move.from_uci("g5g2"),
            Move.from_uci("e4e5"),
            Move.from_uci("f5f6"),
            Move.from_uci("e5e6"),
            Move.from_uci("f6g5"),
            Move.from_uci("e6e5"),
            Move.from_uci("g5g6"),
            Move.from_uci("d5e4"),
            Move.from_uci("c5c4"),
            Move.from_uci("e5c5"),
        ],
    },
]
