# b"{'board': Board('6Q1/ppR3p1/6kp/5p2/3n3K/6P1/P7/5q2 b - - 3 38'), 'limit': Limit(depth=50, nodes=25000000), 'multipv': 5}"
[
    {
        "string": "NNUE evaluation using nn-37f18f62d772.nnue (6MiB, (22528, 128, 15, 32, 1))",
        "depth": 28,
        "seldepth": 2,
        "multipv": 1,
        "score": PovScore(Mate(+1), BLACK),
        "nodes": 25000142,
        "nps": 913213,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 27.376,
        "pv": [Move.from_uci("d4f3")],
        "currmove": Move.from_uci("d4e6"),
        "currmovenumber": 3,
    },
    {
        "depth": 28,
        "seldepth": 2,
        "multipv": 2,
        "score": PovScore(Mate(+1), BLACK),
        "nodes": 25000142,
        "nps": 913213,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 27.376,
        "pv": [Move.from_uci("f1h1")],
    },
    {
        "depth": 27,
        "seldepth": 58,
        "multipv": 3,
        "score": PovScore(Cp(-502), BLACK),
        "nodes": 25000142,
        "nps": 913213,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 27.376,
        "pv": [
            Move.from_uci("d4e6"),
            Move.from_uci("g8e6"),
            Move.from_uci("g6h7"),
            Move.from_uci("e6d5"),
            Move.from_uci("f1f2"),
            Move.from_uci("h4h3"),
            Move.from_uci("f2f1"),
            Move.from_uci("d5g2"),
            Move.from_uci("f1d1"),
            Move.from_uci("h3h2"),
            Move.from_uci("d1h5"),
            Move.from_uci("h2g1"),
            Move.from_uci("h5g6"),
            Move.from_uci("c7c2"),
            Move.from_uci("a7a5"),
            Move.from_uci("c2f2"),
            Move.from_uci("g6e6"),
            Move.from_uci("g2f3"),
            Move.from_uci("h7g6"),
            Move.from_uci("g1g2"),
            Move.from_uci("b7b5"),
            Move.from_uci("f2e2"),
            Move.from_uci("e6f7"),
            Move.from_uci("f3c6"),
            Move.from_uci("g6h7"),
            Move.from_uci("e2f2"),
            Move.from_uci("b5b4"),
            Move.from_uci("c6f3"),
            Move.from_uci("h7g6"),
            Move.from_uci("g3g4"),
            Move.from_uci("f5f4"),
            Move.from_uci("f3f4"),
            Move.from_uci("f7f4"),
            Move.from_uci("f2f4"),
            Move.from_uci("b4b3"),
            Move.from_uci("a2b3"),
            Move.from_uci("h6h5"),
            Move.from_uci("f4a4"),
        ],
    },
    {
        "depth": 27,
        "seldepth": 13,
        "multipv": 4,
        "score": PovScore(Mate(-6), BLACK),
        "nodes": 25000142,
        "nps": 913213,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 27.376,
        "pv": [
            Move.from_uci("f1f4"),
            Move.from_uci("g3f4"),
            Move.from_uci("d4f3"),
            Move.from_uci("h4g3"),
            Move.from_uci("f3g5"),
            Move.from_uci("g8g7"),
            Move.from_uci("g6h5"),
            Move.from_uci("f4g5"),
            Move.from_uci("f5f4"),
            Move.from_uci("g3f4"),
            Move.from_uci("h6g5"),
            Move.from_uci("g7g5"),
        ],
    },
    {
        "depth": 27,
        "seldepth": 9,
        "multipv": 5,
        "score": PovScore(Mate(-4), BLACK),
        "nodes": 25000142,
        "nps": 913213,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 27.376,
        "pv": [
            Move.from_uci("f1h3"),
            Move.from_uci("h4h3"),
            Move.from_uci("g6f6"),
            Move.from_uci("g8g7"),
            Move.from_uci("f6e6"),
            Move.from_uci("g7e7"),
            Move.from_uci("e6d5"),
            Move.from_uci("c7c5"),
        ],
    },
]
