# b"{'board': Board('3R3Q/1p2rk1p/p1p3p1/5p2/4p2q/7P/P4PP1/6K1 w - - 0 32'), 'limit': Limit(depth=50, nodes=25000000), 'multipv': 5}"
[
    {
        "string": "NNUE evaluation using nn-37f18f62d772.nnue (6MiB, (22528, 128, 15, 32, 1))",
        "depth": 29,
        "seldepth": 64,
        "multipv": 1,
        "score": PovScore(Cp(+562), WHITE),
        "nodes": 25000364,
        "nps": 866143,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 28.864,
        "pv": [
            Move.from_uci("g2g3"),
            Move.from_uci("h4h6"),
            Move.from_uci("h8g8"),
            Move.from_uci("f7f6"),
            Move.from_uci("d8d6"),
            Move.from_uci("f6g5"),
            Move.from_uci("g8d8"),
            Move.from_uci("h6h3"),
            Move.from_uci("d8e7"),
            Move.from_uci("g5g4"),
            Move.from_uci("e7b7"),
            Move.from_uci("c6c5"),
            Move.from_uci("b7d5"),
            Move.from_uci("g4h5"),
            Move.from_uci("d5c5"),
            Move.from_uci("a6a5"),
            Move.from_uci("c5e3"),
            Move.from_uci("h3g4"),
            Move.from_uci("g1g2"),
            Move.from_uci("a5a4"),
            Move.from_uci("f2f3"),
            Move.from_uci("e4f3"),
            Move.from_uci("g2f2"),
            Move.from_uci("g4c4"),
            Move.from_uci("e3f3"),
            Move.from_uci("c4g4"),
            Move.from_uci("d6d7"),
        ],
        "currmove": Move.from_uci("g2g3"),
        "currmovenumber": 1,
    },
    {
        "depth": 29,
        "seldepth": 54,
        "multipv": 2,
        "score": PovScore(Cp(+315), WHITE),
        "nodes": 25000364,
        "nps": 866143,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 28.864,
        "pv": [
            Move.from_uci("h8g8"),
            Move.from_uci("f7f6"),
            Move.from_uci("d8d6"),
            Move.from_uci("f6g5"),
            Move.from_uci("g8f8"),
            Move.from_uci("g5h5"),
            Move.from_uci("g2g3"),
            Move.from_uci("h4g5"),
            Move.from_uci("h3h4"),
            Move.from_uci("g5c1"),
            Move.from_uci("g1g2"),
            Move.from_uci("c1a3"),
            Move.from_uci("f8e7"),
            Move.from_uci("a3f3"),
            Move.from_uci("g2f1"),
            Move.from_uci("f3h1"),
            Move.from_uci("f1e2"),
            Move.from_uci("h1f3"),
            Move.from_uci("e2e1"),
            Move.from_uci("f3h1"),
            Move.from_uci("e1d2"),
            Move.from_uci("h5g4"),
            Move.from_uci("e7e5"),
            Move.from_uci("g4h3"),
            Move.from_uci("e5c3"),
            Move.from_uci("h1b1"),
            Move.from_uci("g3g4"),
            Move.from_uci("h3h2"),
            Move.from_uci("g4f5"),
            Move.from_uci("g6f5"),
            Move.from_uci("d2e3"),
            Move.from_uci("b1g1"),
            Move.from_uci("d6d2"),
            Move.from_uci("h7h5"),
            Move.from_uci("d2c2"),
            Move.from_uci("b7b6"),
            Move.from_uci("c3e5"),
            Move.from_uci("h2h1"),
            Move.from_uci("e5f5"),
            Move.from_uci("g1e1"),
            Move.from_uci("e3f4"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 26,
        "multipv": 3,
        "score": PovScore(Cp(0), WHITE),
        "nodes": 25000364,
        "nps": 866143,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 28.864,
        "pv": [
            Move.from_uci("d8f8"),
            Move.from_uci("f7e6"),
            Move.from_uci("g2g3"),
            Move.from_uci("h4g5"),
            Move.from_uci("h8d4"),
            Move.from_uci("f5f4"),
            Move.from_uci("f8f4"),
            Move.from_uci("g5d5"),
            Move.from_uci("f4e4"),
            Move.from_uci("e6d7"),
            Move.from_uci("e4e7"),
            Move.from_uci("d7e7"),
            Move.from_uci("d4h4"),
            Move.from_uci("e7d6"),
            Move.from_uci("h4h7"),
            Move.from_uci("d5d1"),
            Move.from_uci("g1g2"),
            Move.from_uci("d1b1"),
            Move.from_uci("h3h4"),
            Move.from_uci("b1e4"),
            Move.from_uci("g2h2"),
            Move.from_uci("e4f5"),
            Move.from_uci("h2g1"),
            Move.from_uci("f5b1"),
            Move.from_uci("g1g2"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 9,
        "multipv": 4,
        "score": PovScore(Cp(0), WHITE),
        "nodes": 25000364,
        "nps": 866143,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 28.864,
        "pv": [
            Move.from_uci("h8f8"),
            Move.from_uci("f7e6"),
            Move.from_uci("g2g3"),
            Move.from_uci("h4h3"),
            Move.from_uci("f8g8"),
            Move.from_uci("e6f6"),
            Move.from_uci("g8f8"),
            Move.from_uci("f6e6"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 53,
        "multipv": 5,
        "score": PovScore(Cp(-53), WHITE),
        "nodes": 25000364,
        "nps": 866113,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 28.865,
        "pv": [
            Move.from_uci("a2a4"),
            Move.from_uci("e4e3"),
            Move.from_uci("g2g3"),
            Move.from_uci("e3e2"),
            Move.from_uci("h8g8"),
            Move.from_uci("f7f6"),
            Move.from_uci("g8f8"),
            Move.from_uci("f6e6"),
            Move.from_uci("g3h4"),
            Move.from_uci("e2e1q"),
            Move.from_uci("g1g2"),
            Move.from_uci("e1e4"),
            Move.from_uci("g2g1"),
            Move.from_uci("e4h4"),
            Move.from_uci("d8d3"),
            Move.from_uci("h4g5"),
            Move.from_uci("g1f1"),
            Move.from_uci("g5c1"),
            Move.from_uci("f1g2"),
            Move.from_uci("f5f4"),
            Move.from_uci("f8g8"),
            Move.from_uci("e7f7"),
            Move.from_uci("g8e8"),
            Move.from_uci("e6f6"),
            Move.from_uci("h3h4"),
            Move.from_uci("c1c5"),
            Move.from_uci("e8h8"),
            Move.from_uci("f7g7"),
            Move.from_uci("h8b8"),
            Move.from_uci("f6f5"),
        ],
    },
]
