# b"{'board': Board('8/R4p2/4p1k1/1PK5/3P4/8/1r6/8 w - - 5 45'), 'limit': Limit(depth=50, nodes=25000000), 'multipv': 5}"
[
    {
        "string": "NNUE evaluation using nn-37f18f62d772.nnue (6MiB, (22528, 128, 15, 32, 1))",
        "depth": 29,
        "seldepth": 67,
        "multipv": 1,
        "score": PovScore(Cp(+479), WHITE),
        "nodes": 25000513,
        "nps": 1006664,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 24.835,
        "pv": [
            Move.from_uci("a7a4"),
            Move.from_uci("e6e5"),
            Move.from_uci("b5b6"),
            Move.from_uci("e5d4"),
            Move.from_uci("a4b4"),
            Move.from_uci("b2c2"),
            Move.from_uci("c5d4"),
            Move.from_uci("c2c8"),
            Move.from_uci("b6b7"),
            Move.from_uci("c8b8"),
            Move.from_uci("d4d5"),
            Move.from_uci("f7f5"),
            Move.from_uci("d5c6"),
            Move.from_uci("g6f6"),
            Move.from_uci("c6d6"),
            Move.from_uci("b8d8"),
            Move.from_uci("d6c7"),
            Move.from_uci("d8h8"),
            Move.from_uci("b7b8q"),
            Move.from_uci("h8b8"),
            Move.from_uci("b4b8"),
            Move.from_uci("f6e5"),
            Move.from_uci("c7c6"),
            Move.from_uci("f5f4"),
            Move.from_uci("c6c5"),
            Move.from_uci("e5e4"),
            Move.from_uci("c5c4"),
            Move.from_uci("e4e3"),
            Move.from_uci("c4c3"),
            Move.from_uci("e3e4"),
            Move.from_uci("b8b4"),
            Move.from_uci("e4d5"),
            Move.from_uci("b4d4"),
            Move.from_uci("d5e5"),
            Move.from_uci("c3d3"),
            Move.from_uci("f4f3"),
            Move.from_uci("d4e4"),
            Move.from_uci("e5d5"),
            Move.from_uci("e4b4"),
            Move.from_uci("f3f2"),
            Move.from_uci("d3e2"),
            Move.from_uci("d5c6"),
        ],
        "currmove": Move.from_uci("c5c6"),
        "currmovenumber": 4,
    },
    {
        "depth": 29,
        "seldepth": 61,
        "multipv": 2,
        "score": PovScore(Cp(+478), WHITE),
        "nodes": 25000513,
        "nps": 1006664,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 24.835,
        "pv": [
            Move.from_uci("b5b6"),
            Move.from_uci("b2c2"),
            Move.from_uci("c5b5"),
            Move.from_uci("c2b2"),
            Move.from_uci("b5a6"),
            Move.from_uci("b2a2"),
            Move.from_uci("a6b7"),
            Move.from_uci("a2b2"),
            Move.from_uci("a7a5"),
            Move.from_uci("f7f5"),
            Move.from_uci("b7c6"),
            Move.from_uci("f5f4"),
            Move.from_uci("b6b7"),
            Move.from_uci("f4f3"),
            Move.from_uci("a5a3"),
            Move.from_uci("g6f5"),
            Move.from_uci("a3f3"),
            Move.from_uci("f5e4"),
            Move.from_uci("f3f6"),
            Move.from_uci("e6e5"),
            Move.from_uci("d4e5"),
            Move.from_uci("e4e5"),
            Move.from_uci("f6f8"),
            Move.from_uci("b2c2"),
            Move.from_uci("c6d7"),
            Move.from_uci("c2b2"),
            Move.from_uci("d7c7"),
            Move.from_uci("b2c2"),
            Move.from_uci("c7b8"),
            Move.from_uci("e5d4"),
            Move.from_uci("f8f6"),
            Move.from_uci("c2b2"),
            Move.from_uci("b8c7"),
            Move.from_uci("b2b7"),
            Move.from_uci("c7b7"),
            Move.from_uci("d4e4"),
            Move.from_uci("b7c6"),
            Move.from_uci("e4d3"),
            Move.from_uci("c6b5"),
            Move.from_uci("d3e4"),
            Move.from_uci("b5c4"),
            Move.from_uci("e4e5"),
            Move.from_uci("f6f2"),
            Move.from_uci("e5e4"),
            Move.from_uci("f2f8"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 71,
        "multipv": 3,
        "score": PovScore(Cp(+39), WHITE),
        "nodes": 25000513,
        "nps": 1006664,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 24.835,
        "pv": [
            Move.from_uci("a7a6"),
            Move.from_uci("b2c2"),
            Move.from_uci("c5d6"),
            Move.from_uci("c2b2"),
            Move.from_uci("b5b6"),
            Move.from_uci("g6f5"),
            Move.from_uci("d6c7"),
            Move.from_uci("b2c2"),
            Move.from_uci("c7d7"),
            Move.from_uci("c2b2"),
            Move.from_uci("a6a5"),
            Move.from_uci("f5e4"),
            Move.from_uci("d7c6"),
            Move.from_uci("e4d4"),
            Move.from_uci("a5b5"),
            Move.from_uci("b2g2"),
            Move.from_uci("b6b7"),
            Move.from_uci("g2g8"),
            Move.from_uci("b7b8q"),
            Move.from_uci("g8b8"),
            Move.from_uci("b5b8"),
            Move.from_uci("f7f5"),
            Move.from_uci("b8b4"),
            Move.from_uci("d4e3"),
            Move.from_uci("c6d6"),
            Move.from_uci("f5f4"),
            Move.from_uci("d6e5"),
            Move.from_uci("f4f3"),
            Move.from_uci("b4b3"),
            Move.from_uci("e3e2"),
            Move.from_uci("e5f4"),
            Move.from_uci("f3f2"),
            Move.from_uci("b3b2"),
            Move.from_uci("e2e1"),
            Move.from_uci("f4e3"),
            Move.from_uci("f2f1n"),
            Move.from_uci("e3f3"),
        ],
    },
    {
        "depth": 29,
        "seldepth": 50,
        "multipv": 4,
        "score": PovScore(Cp(+38), WHITE),
        "nodes": 25000513,
        "nps": 1006664,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 24.835,
        "pv": [Move.from_uci("c5c6"), Move.from_uci("b2c2")],
        "upperbound": True,
    },
    {
        "depth": 28,
        "seldepth": 50,
        "multipv": 5,
        "score": PovScore(Cp(+17), WHITE),
        "nodes": 25000513,
        "nps": 1006664,
        "hashfull": 1000,
        "tbhits": 0,
        "time": 24.835,
        "pv": [
            Move.from_uci("a7a5"),
            Move.from_uci("f7f5"),
            Move.from_uci("c5c6"),
            Move.from_uci("f5f4"),
            Move.from_uci("b5b6"),
            Move.from_uci("f4f3"),
            Move.from_uci("b6b7"),
            Move.from_uci("f3f2"),
            Move.from_uci("a5a1"),
            Move.from_uci("b2c2"),
            Move.from_uci("c6d6"),
            Move.from_uci("c2b2"),
            Move.from_uci("a1f1"),
            Move.from_uci("b2b7"),
            Move.from_uci("f1f2"),
            Move.from_uci("b7b6"),
            Move.from_uci("d6e5"),
            Move.from_uci("g6g7"),
            Move.from_uci("f2f3"),
            Move.from_uci("b6a6"),
            Move.from_uci("f3f1"),
            Move.from_uci("a6a4"),
            Move.from_uci("e5e6"),
            Move.from_uci("a4d4"),
            Move.from_uci("f1b1"),
            Move.from_uci("d4a4"),
            Move.from_uci("b1g1"),
            Move.from_uci("g7f8"),
        ],
    },
]
